Aim: To apply support vector machine for classification and analyze the impact of different on model accuracy.
Name: Vaishnavi Sandokar
USN : CS24D007

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path="/content/drive/MyDrive/ML /pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.describe()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
count,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000
mean,111.079968,46.549532,0.477857,1.770279,12.614400,26.326515,8.303556,104.857709,0.091574
std,25.652935,6.843189,1.064040,6.167913,29.472897,19.470572,4.506092,106.514540,0.288432
min,5.812500,24.772042,-1.876011,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.929688,42.376018,0.027098,-0.188572,1.923077,14.437332,5.781506,34.960504,0.000000
50%,115.078125,46.947479,0.223240,0.198710,2.801839,18.461316,8.433515,83.064556,0.000000
75%,127.085938,51.023202,0.473325,0.927783,5.464256,28.428104,10.702959,139.309330,0.000000
max,192.617188,98.778911,8.069522,68.101622,223.392141,110.642211,34.539844,1191.000837,1.000000

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0    Mean of the integrated profile                17898 non-null  float64
 1    Standard deviation of the integrated profile  17898 non-null  float64
 2    Excess kurtosis of the integrated profile     17898 non-null  float64
 3    Skewness of the integrated profile            17898 non-null  float64
 4    Mean of the DM-SNR curve                      17898 non-null  float64
 5    Standard deviation of the DM-SNR curve        17898 non-null  float64
 6    Excess kurtosis of the DM-SNR curve           17898 non-null  float64
 7    Skewness of the DM-SNR curve                  17898 non-null  float64
 8   target_class                                   17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [ ]:
df.columns

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve', ' Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.replace(' ', '')

In [ ]:
df.columns

Index(['Meanoftheintegratedprofile', 'Standarddeviationoftheintegratedprofile',
       'Excesskurtosisoftheintegratedprofile',
       'Skewnessoftheintegratedprofile', 'MeanoftheDM-SNRcurve',
       'StandarddeviationoftheDM-SNRcurve', 'ExcesskurtosisoftheDM-SNRcurve',
       'SkewnessoftheDM-SNRcurve', 'target_class'],
      dtype='object')

In [ ]:
df.columns=[' Mean ','Standard ','Excess','Skewness','Standard ','Excess','Skewness','target','dtype']

In [ ]:
df.column=['Mean','Standard',]

In [ ]:
df.columns

Index([' Mean ', 'Standard ', 'Excess', 'Skewness', 'Standard ', 'Excess',
       'Skewness', 'target', 'dtype'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [ Mean , Standard , Excess, Skewness, Standard , Excess, Skewness, target, dtype]
Index: []

In [ ]:
df.shape

(17898, 9)

In [ ]:
before_rows=df.shape[0]
df=df.dropna()
after_rows=df.shape[0]
print('before_rows:',before_rows)
print('after_rows:',after_rows)
print("the number of dropped rows are:", before_rows-after_rows)

before_rows: 17898
after_rows: 17898
the number of dropped rows are: 0

In [ ]:
df.shape

(17898, 9)

In [ ]:
X.head

<bound method NDFrame.head of        Mean of the integrated profile  \
0                          140.562500
1                          102.507812
2                          103.015625
3                          136.750000
4                           88.726562
...                               ...
17893                      136.429688
17894                      122.554688
17895                      119.335938
17896                      114.507812
17897                       57.062500

       Standard deviation of the integrated profile  \
0                                         55.683782
1                                         58.882430
2                                         39.341649
3                                         57.178449
4                                         40.672225
...                                             ...
17893                                     59.847421
17894                                     49.485605
17895                                     59.935939
17896                                     53.902400
17897                                     85.797340

       Excess kurtosis of the integrated profile  \
0                                      -0.234571
1                                       0.465318
2                                       0.323328
3                                      -0.068415
4                                       0.600866
...                                          ...
17893                                  -0.187846
17894                                   0.127978
17895                                   0.159363
17896                                   0.201161
17897                                   1.406391

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
0                               -0.699648                  3.199833
1                               -0.515088                  1.677258
2                                1.051164                  3.121237
3                               -0.636238                  3.642977
4                                1.123492                  1.178930
...                                   ...                       ...
17893                           -0.738123                  1.296823
17894                            0.323061                 16.409699
17895                           -0.743025                 21.430602
17896                           -0.024789                  1.946488
17897                            0.089520                188.306020

       Standard deviation of the DM-SNR curve  \
0                                   19.110426
1                                   14.860146
2                                   21.744669
3                                   20.959280
4                                   11.468720
...                                       ...
17893                               12.166062
17894                               44.626893
17895                               58.872000
17896                               13.381731
17897                               64.712562

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve
0                                 7.975532                     74.242225
1                                10.576487                    127.393580
2                                 7.735822                     63.171909
3                                 6.896499                     53.593661
4                                14.269573                    252.567306
...                                    ...                           ...
17893                            15.450260                    285.931022
17894                             2.945244                      8.297092
17895                             2.499517                      4.595173
17896                            10.007967                    134.238910
17897                            -1.597527                      1.429475

[17898 rows x 8 columns]>

In [ ]:

X_train.columns = X_train.columns.str.replace(' ', '')
cols = X_train.columns
print(cols)

Index(['Meanoftheintegratedprofile', 'Standarddeviationoftheintegratedprofile',
       'Excesskurtosisoftheintegratedprofile',
       'Skewnessoftheintegratedprofile', 'MeanoftheDM-SNRcurve',
       'StandarddeviationoftheDM-SNRcurve', 'ExcesskurtosisoftheDM-SNRcurve',
       'SkewnessoftheDM-SNRcurve'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [ ]:
X_train

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
12223,121.156250,48.372971,0.375485,-0.013165,3.168896,18.399367,7.449874,65.159298
1919,76.968750,36.175557,0.712898,3.388719,2.399666,17.570997,9.414652,102.722975
2753,130.585938,53.229534,0.133408,-0.297242,2.743311,22.362553,8.508364,74.031324
17220,156.398438,48.865942,-0.215989,-0.171294,17.471572,54.469915,2.958066,7.197842
12110,84.804688,36.117659,0.825013,3.274125,2.790134,20.618009,8.405008,76.291128
...,...,...,...,...,...,...,...,...
11284,124.312500,53.179053,-0.012418,-0.556021,7.186455,29.308266,4.531382,21.725143
11964,115.617188,46.784600,0.218177,0.226757,6.140468,30.271961,5.732201,34.357282
5390,116.031250,43.213846,0.663456,0.433088,0.785117,11.628149,17.055215,312.204325
860,135.664062,49.933749,-0.089940,-0.226726,3.859532,21.501505,7.398395,62.334018
15795,120.726562,50.472256,0.346178,0.184797,0.769231,11.792603,17.662222,329.548016

In [ ]:
X_test

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
15985,116.906250,48.920605,0.186046,-0.129815,3.037625,17.737102,8.122621,78.813405
8188,75.585938,34.386254,2.025498,8.652913,3.765050,21.897049,7.048189,55.878791
8157,103.273438,46.996628,0.504295,0.821088,2.244983,15.622566,9.330498,105.134941
2589,101.078125,48.587487,1.011427,1.151870,81.887960,81.464136,0.485105,-1.117904
11909,113.226562,48.608804,0.291538,0.292120,6.291806,26.585056,4.540138,21.708268
...,...,...,...,...,...,...,...,...
12653,116.531250,51.140269,-0.001220,-0.184189,4.510870,26.599514,6.634989,45.362390
6454,114.976562,53.783052,0.377599,-0.155708,2.772575,20.838488,8.440796,77.355028
530,136.171875,48.924385,-0.019473,0.063227,2.810201,18.695230,7.848577,69.388978
1540,106.500000,49.066122,0.245742,0.140377,2.331104,15.417568,9.008041,100.367616
6921,110.679688,38.252642,0.459937,1.690689,4.434783,22.201794,5.939747,39.781374

In [ ]:
y_test

15985    0
8188     1
8157     0
2589     1
11909    0
        ..
12653    0
6454     0
530      0
1540     0
6921     1
Name: target_class, Length: 5370, dtype: int64

In [ ]:
y_train

12223    0
1919     0
2753     0
17220    0
12110    0
        ..
11284    0
11964    0
5390     0
860      0
15795    0
Name: target_class, Length: 12528, dtype: int64

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(X_train,y_train)
X_test.columns = X_test.columns.str.replace(' ', '')
y_pred=svc.predict(X_test)
print('Model accuracy score with default hyperparamenters:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with default hyperparamenters:{0:0.4f} 0.9728119180633147

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('confusion_matrix')
cm = confusion_matrix(y_test,y_pred)
print(cm)

confusion_matrix
[[4861   23]
 [ 123  363]]

In [ ]:
print('accuracy_score')
print(accuracy_score(y_test,y_pred))

accuracy_score
0.9728119180633147

In [ ]:
from sklearn.metrics import classification_report
print('classification_report')
print(classification_report(y_test,y_pred))

classification_report
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4884
           1       0.94      0.75      0.83       486

    accuracy                           0.97      5370
   macro avg       0.96      0.87      0.91      5370
weighted avg       0.97      0.97      0.97      5370

In [ ]:
svc=SVC(C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0:{0:0.4f} 0.9780260707635009

In [ ]:
svc=SVC(C=1200.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=1200.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1200.0:{0:0.4f} 0.9793296089385475

In [ ]:
linear_kernel=SVC(kernel='linear',C=1.0)
linear_kernel.fit(X_train,y_train)
y_pred_test =linear_kernel.predict(X_test)

In [ ]:
poly_svc=SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train,y_train)
y_pred_test =poly_svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=1.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1.0:{0:0.4f} 0.9793296089385475

In [ ]:
sigmoid_csv=SVC(kernel='sigmoid',C=100)
sigmoid_csv.fit(X_train,y_train)
y_pred =sigmoid_csv.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0,gamma=1.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0,gamma=1.0:{0:0.4f} 0.9208566108007449

In [ ]:
sigmoid_csv=SVC(kernel='sigmoid',C=1000)
sigmoid_csv.fit(X_train,y_train)
y_pred =sigmoid_csv.predict(X_test)
print('Model accuracy score with rbf kernel and C=1000.0,gamma=1.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1000.0,gamma=1.0:{0:0.4f} 0.9208566108007449