Aim: To design and implement an Artificial Neural Network for
classification problem and evaluate its learning performance.
Name :Vaishnavi Sandokar

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path= "/content/drive/MyDrive/ML /churn.csv"
df=pd.read_csv(path)
df.head(5)

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
df.describe()

         RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [RowNumber, CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [ ]:
df.shape

(10000, 14)

In [ ]:
before_rows=df.shape[0]
df=df.dropna()
after_rows=df.shape[0]
print('before_rows:',before_rows)
print('after_rows:',after_rows)
print("the number of dropped rows are:", before_rows-after_rows)

before_rows: 10000
after_rows: 10000
the number of dropped rows are: 0

In [ ]:
df.shape

(10000, 14)

In [ ]:
df=pd.read_csv(path)
X=df.drop(columns=['Exited'])
y=df['Exited']

In [ ]:
X

      RowNumber  CustomerId  ... IsActiveMember  EstimatedSalary
0             1    15634602  ...              1        101348.88
1             2    15647311  ...              1        112542.58
2             3    15619304  ...              0        113931.57
3             4    15701354  ...              0         93826.63
4             5    15737888  ...              1         79084.10
...         ...         ...  ...            ...              ...
9995       9996    15606229  ...              0         96270.64
9996       9997    15569892  ...              1        101699.77
9997       9998    15584532  ...              1         42085.58
9998       9999    15682355  ...              0         92888.52
9999      10000    15628319  ...              0         38190.78

[10000 rows x 13 columns]

In [ ]:
X.head

<bound method NDFrame.head of       RowNumber  CustomerId  ... IsActiveMember  EstimatedSalary
0             1    15634602  ...              1        101348.88
1             2    15647311  ...              1        112542.58
2             3    15619304  ...              0        113931.57
3             4    15701354  ...              0         93826.63
4             5    15737888  ...              1         79084.10
...         ...         ...  ...            ...              ...
9995       9996    15606229  ...              0         96270.64
9996       9997    15569892  ...              1        101699.77
9997       9998    15584532  ...              1         42085.58
9998       9999    15682355  ...              0         92888.52
9999      10000    15628319  ...              0         38190.78

[10000 rows x 13 columns]>

In [ ]:
X = pd.get_dummies(X,dtype = int)

In [ ]:
X

      RowNumber  CustomerId  ...  Gender_Female  Gender_Male
0             1    15634602  ...              1            0
1             2    15647311  ...              1            0
2             3    15619304  ...              1            0
3             4    15701354  ...              1            0
4             5    15737888  ...              1            0
...         ...         ...  ...            ...          ...
9995       9996    15606229  ...              0            1
9996       9997    15569892  ...              0            1
9997       9998    15584532  ...              1            0
9998       9999    15682355  ...              0            1
9999      10000    15628319  ...              1            0

[10000 rows x 2947 columns]

In [ ]:
X.head()

   RowNumber  CustomerId  ...  Gender_Female  Gender_Male
0          1    15634602  ...              1            0
1          2    15647311  ...              1            0
2          3    15619304  ...              1            0
3          4    15701354  ...              1            0
4          5    15737888  ...              1            0

[5 rows x 2947 columns]

In [ ]:
X.shape

(10000, 2947)

In [ ]:
X.columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       ...
       'Surname_Zubarev', 'Surname_Zubareva', 'Surname_Zuev', 'Surname_Zuyev',
       'Surname_Zuyeva', 'Geography_France', 'Geography_Germany',
       'Geography_Spain', 'Gender_Female', 'Gender_Male'],
      dtype='object', length=2947)

In [ ]:
X = df.iloc[:,3:-1]
print(X)

      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [ ]:
y=df.iloc[:,-1]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
X = pd.get_dummies(X,dtype = int)
X

      CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 13 columns]

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,test_size=0.3,random_state = 42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7000, 13), (3000, 13), (7000,), (3000,))

In [ ]:
X_train,X_test,y_train,y_test

(      CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
 9069          619   32       4  ...                1              1            0
 2603          643   34       7  ...                0              1            0
 7738          561   33       6  ...                0              0            1
 1579          618   41       8  ...                0              0            1
 5058          714   37       9  ...                0              0            1
 ...           ...  ...     ...  ...              ...            ...          ...
 5734          768   54       8  ...                0              0            1
 5191          682   58       1  ...                0              1            0
 5390          735   38       1  ...                0              1            0
 860           667   43       8  ...                0              0            1
 7270          697   51       1  ...                0              0            1

 [7000 rows x 13 columns],
       CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
 6252          596   32       3  ...                0              0            1
 4684          623   43       1  ...                0              0            1
 1731          601   44       4  ...                1              1            0
 4742          506   59       8  ...                0              0            1
 4521          560   27       7  ...                1              1            0
 ...           ...  ...     ...  ...              ...            ...          ...
 8014          731   39       2  ...                1              1            0
 1074          535   31       7  ...                0              1            0
 3063          609   32       7  ...                0              0            1
 6487          580   31       2  ...                0              0            1
 4705          533   22      10  ...                0              1            0

 [3000 rows x 13 columns],
 9069    1
 2603    0
 7738    0
 1579    0
 5058    0
        ..
 5734    0
 5191    0
 5390    1
 860     1
 7270    0
 Name: Exited, Length: 7000, dtype: int64,
 6252    0
 4684    0
 1731    0
 4742    0
 4521    0
        ..
 8014    0
 1074    0
 3063    0
 6487    0
 4705    0
 Name: Exited, Length: 3000, dtype: int64)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_test

array([[-0.5836166 , -0.65674999, -0.68894811, ..., -0.57779016,
        -0.91055421,  0.91055421],
       [-0.30302599,  0.39028611, -1.38250341, ..., -0.57779016,
        -0.91055421,  0.91055421],
       [-0.53165538,  0.48547121, -0.34217046, ...,  1.73073215,
         1.09823226, -1.09823226],
       ...,
       [-0.44851742, -0.65674999,  0.69816249, ..., -0.57779016,
        -0.91055421,  0.91055421],
       [-0.74989252, -0.75193509, -1.03572576, ..., -0.57779016,
        -0.91055421,  0.91055421],
       [-1.23832804, -1.60860099,  1.73849544, ..., -0.57779016,
         1.09823226, -1.09823226]])

In [ ]:
X_train

array([[-0.34459497, -0.65674999, -0.34217046, ...,  1.73073215,
         1.09823226, -1.09823226],
       [-0.09518109, -0.46637979,  0.69816249, ..., -0.57779016,
         1.09823226, -1.09823226],
       [-0.94734518, -0.56156489,  0.35138484, ..., -0.57779016,
        -0.91055421,  0.91055421],
       ...,
       [ 0.86090545, -0.08563939, -1.38250341, ..., -0.57779016,
         1.09823226, -1.09823226],
       [ 0.15423279,  0.39028611,  1.04494014, ..., -0.57779016,
        -0.91055421,  0.91055421],
       [ 0.46600014,  1.1517669 , -1.38250341, ..., -0.57779016,
        -0.91055421,  0.91055421]])

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.4953 - loss: 0.7737
Epoch 2/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7592 - loss: 0.5254
Epoch 3/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7956 - loss: 0.4804
Epoch 4/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8070 - loss: 0.4572
Epoch 5/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8088 - loss: 0.4448
Epoch 6/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8123 - loss: 0.4407
Epoch 7/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8109 - loss: 0.4256
Epoch 8/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8096 - loss: 0.4318
Epoch 9/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7963 - loss: 0.4465
Epoch 10/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8136 - loss: 0.4314
Epoch 11/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8210 - loss: 0.4168
Epoch 12/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8137 - loss: 0.4141
Epoch 13/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8187 - loss: 0.4171
Epoch 14/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8254 - loss: 0.4049
Epoch 15/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8298 - loss: 0.3889
Epoch 16/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8287 - loss: 0.3902
Epoch 17/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8474 - loss: 0.3630
Epoch 18/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8451 - loss: 0.3728
Epoch 19/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8492 - loss: 0.3610
Epoch 20/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8561 - loss: 0.3513
Epoch 21/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8484 - loss: 0.3576
Epoch 22/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8521 - loss: 0.3542
Epoch 23/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8475 - loss: 0.3640
Epoch 24/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8584 - loss: 0.3456
Epoch 25/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8590 - loss: 0.3423
Epoch 26/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8632 - loss: 0.3443
Epoch 27/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8565 - loss: 0.3395
Epoch 28/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8590 - loss: 0.3453
Epoch 29/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8644 - loss: 0.3389
Epoch 30/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8505 - loss: 0.3522
Epoch 31/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8545 - loss: 0.3452
Epoch 32/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8517 - loss: 0.3524
Epoch 33/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8564 - loss: 0.3381
Epoch 34/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8637 - loss: 0.3329
Epoch 35/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8557 - loss: 0.3508
Epoch 36/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8510 - loss: 0.3494
Epoch 37/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8588 - loss: 0.3442
Epoch 38/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8626 - loss: 0.3370
Epoch 39/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8515 - loss: 0.3492
Epoch 40/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8585 - loss: 0.3422
Epoch 41/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8552 - loss: 0.3486
Epoch 42/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8674 - loss: 0.3266
Epoch 43/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8633 - loss: 0.3300
Epoch 44/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8548 - loss: 0.3542
Epoch 45/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8611 - loss: 0.3427
Epoch 46/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8675 - loss: 0.3317
Epoch 47/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8642 - loss: 0.3360
Epoch 48/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8702 - loss: 0.3213
Epoch 49/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8576 - loss: 0.3391
Epoch 50/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8583 - loss: 0.3401
Epoch 51/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8561 - loss: 0.3394
Epoch 52/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8624 - loss: 0.3445
Epoch 53/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8601 - loss: 0.3359
Epoch 54/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8585 - loss: 0.3417
Epoch 55/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8568 - loss: 0.3450
Epoch 56/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3304
Epoch 57/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8572 - loss: 0.3442
Epoch 58/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8500 - loss: 0.3580
Epoch 59/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8582 - loss: 0.3428
Epoch 60/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8624 - loss: 0.3390
Epoch 61/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8540 - loss: 0.3550
Epoch 62/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8608 - loss: 0.3428
Epoch 63/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8588 - loss: 0.3313
Epoch 64/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8578 - loss: 0.3364
Epoch 65/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8535 - loss: 0.3454
Epoch 66/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8671 - loss: 0.3288
Epoch 67/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8607 - loss: 0.3408
Epoch 68/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8603 - loss: 0.3394
Epoch 69/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8561 - loss: 0.3435
Epoch 70/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8572 - loss: 0.3362
Epoch 71/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8666 - loss: 0.3273
Epoch 72/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8607 - loss: 0.3429
Epoch 73/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8636 - loss: 0.3342
Epoch 74/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8646 - loss: 0.3318
Epoch 75/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8564 - loss: 0.3539
Epoch 76/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3456
Epoch 77/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8643 - loss: 0.3345
Epoch 78/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8655 - loss: 0.3337
Epoch 79/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3291
Epoch 80/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8603 - loss: 0.3383
Epoch 81/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8579 - loss: 0.3332
Epoch 82/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8635 - loss: 0.3344
Epoch 83/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8567 - loss: 0.3413
Epoch 84/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8679 - loss: 0.3205
Epoch 85/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8621 - loss: 0.3356
Epoch 86/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8572 - loss: 0.3404
Epoch 87/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8632 - loss: 0.3371
Epoch 88/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8595 - loss: 0.3463
Epoch 89/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8598 - loss: 0.3426
Epoch 90/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8578 - loss: 0.3398
Epoch 91/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8600 - loss: 0.3400
Epoch 92/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8629 - loss: 0.3295
Epoch 93/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8603 - loss: 0.3456
Epoch 94/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8669 - loss: 0.3283
Epoch 95/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8528 - loss: 0.3540
Epoch 96/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8580 - loss: 0.3415
Epoch 97/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8590 - loss: 0.3445
Epoch 98/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8632 - loss: 0.3381
Epoch 99/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3423
Epoch 100/100
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8679 - loss: 0.3302

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('confusion_matrix')
cm = confusion_matrix(y_test,y_pred)
print(cm)

confusion_matrix
[[2333   83]
 [ 313  271]]

In [ ]:
print('accuracy_score')
print(accuracy_score(y_test,y_pred))

accuracy_score
0.868

In [ ]:
from sklearn.metrics import classification_report
print('classification_report')
print(classification_report(y_test,y_pred))

classification_report
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      2416
           1       0.77      0.46      0.58       584

    accuracy                           0.87      3000
   macro avg       0.82      0.71      0.75      3000
weighted avg       0.86      0.87      0.85      3000