Aim: To apply support vector machine for classification and analyze the impact of different on model accuracy.
Name: Vaishnavi Sandokar
USN : CS24D007

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path="/content/drive/MyDrive/ML /Student_Performance_dataset_5000.csv"
df=pd.read_csv(path)
df.head(5)

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [ ]:
df.describe()

,student_id,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,20.520400,4.539594,2.478734,2.011984,2.998086,1.564514,7.016492,6.979588,74.535600,251.450400,0.498200,0.501400,5.507400,29.431616,45.615324,37.267716,18.803752
std,1443.520003,2.870406,1.821665,1.177990,0.983906,1.467949,1.110807,1.163692,2.486214,42.932293,143.842712,0.500047,0.500048,2.869145,9.962902,14.246591,16.849397,12.130840
min,1.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1250.750000,18.000000,3.250000,1.660000,1.320000,1.990000,0.670000,6.237500,5.280000,37.000000,129.000000,0.000000,0.000000,3.000000,22.567500,35.727500,25.290000,9.337500
50%,2500.500000,20.000000,4.530000,2.480000,2.010000,2.980000,1.490000,7.010000,6.950000,75.000000,252.000000,0.000000,1.000000,5.000000,29.430000,45.690000,36.860000,18.010000
75%,3750.250000,23.000000,5.760000,3.290000,2.690000,4.030000,2.340000,7.810000,8.710000,112.000000,376.000000,1.000000,1.000000,8.000000,36.242500,55.352500,49.142500,27.400000
max,5000.000000,25.000000,11.840000,7.410000,6.000000,8.280000,5.640000,10.000000,15.300000,149.000000,499.000000,1.000000,1.000000,10.000000,63.480000,97.580000,98.020000,64.090000

In [ ]:
df.shape

(5000, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   object
 3   academic_level        5000 non-null   object
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   int64
 14  upcoming_deadline     5000 non-null   int64
 15  internet_quality      5000 non-null   object
 16  mental_health_score   5000 non-null   int64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(11), int64(7), object(3)
memory usage: 820.4+ KB

In [ ]:
df.columns

Index(['student_id', 'age', 'gender', 'academic_level', 'study_hours',
       'self_study_hours', 'online_classes_hours', 'social_media_hours',
       'gaming_hours', 'sleep_hours', 'screen_time_hours', 'exercise_minutes',
       'caffeine_intake_mg', 'part_time_job', 'upcoming_deadline',
       'internet_quality', 'mental_health_score', 'focus_index',
       'burnout_level', 'productivity_score', 'exam_score'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.replace(' ', '')

In [ ]:
df.columns

Index(['student_id', 'age', 'gender', 'academic_level', 'study_hours',
       'self_study_hours', 'online_classes_hours', 'social_media_hours',
       'gaming_hours', 'sleep_hours', 'screen_time_hours', 'exercise_minutes',
       'caffeine_intake_mg', 'part_time_job', 'upcoming_deadline',
       'internet_quality', 'mental_health_score', 'focus_index',
       'burnout_level', 'productivity_score', 'exam_score'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [student_id, age, gender, academic_level, study_hours, self_study_hours, online_classes_hours, social_media_hours, gaming_hours, sleep_hours, screen_time_hours, exercise_minutes, caffeine_intake_mg, part_time_job, upcoming_deadline, internet_quality, mental_health_score, focus_index, burnout_level, productivity_score, exam_score]
Index: []

[0 rows x 21 columns]

In [ ]:
df.shape

(5000, 21)

In [ ]:
before_rows=df.shape[0]
df=df.dropna()
after_rows=df.shape[0]
print('before_rows:',before_rows)
print('after_rows:',after_rows)
print("the number of dropped rows are:", before_rows-after_rows)

before_rows: 5000
after_rows: 5000
the number of dropped rows are: 0

In [ ]:
df.shape

(5000, 21)

In [ ]:
df.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [ ]:
X_train

,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,...,mental_health_score,focus_index,burnout_level,productivity_score,gender_Male,gender_Other,academic_level_Postgraduate,academic_level_Undergraduate,internet_quality_Good,internet_quality_Poor
4227,23,3.72,1.23,2.59,2.86,1.75,6.69,5.52,132,424,...,8,34.49,58.40,37.90,False,False,False,False,False,False
4676,23,6.27,0.78,1.30,2.75,0.00,7.12,6.55,67,144,...,8,45.53,34.64,60.30,False,True,False,False,False,False
800,18,7.23,1.97,3.13,2.80,2.06,6.18,9.83,10,433,...,7,35.48,53.50,61.49,False,True,False,False,False,True
3671,20,2.19,1.61,1.70,1.43,1.94,8.77,6.28,31,450,...,6,24.02,36.40,23.14,True,False,False,False,True,False
4193,17,3.11,4.04,1.14,2.22,0.95,6.61,3.27,124,128,...,6,36.39,40.93,42.99,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,18,4.30,2.34,0.70,0.43,4.04,7.39,7.81,122,87,...,2,36.18,40.42,31.42,False,True,True,False,False,True
466,25,3.85,2.63,2.30,2.55,2.46,8.15,6.81,34,453,...,10,38.26,57.39,45.30,False,True,False,False,False,False
3092,17,6.55,2.90,3.11,3.42,2.44,6.17,6.08,142,173,...,7,34.70,56.14,47.66,False,True,False,False,False,True
3772,21,4.16,0.00,1.27,4.01,3.41,8.07,10.80,135,152,...,7,21.78,48.07,43.06,True,False,True,False,False,True
860,18,3.96,0.98,1.77,4.35,2.22,6.57,8.89,43,154,...,3,16.28,36.62,21.36,True,False,True,False,False,True

In [ ]:
X_test

,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,...,mental_health_score,focus_index,burnout_level,productivity_score,gender_Male,gender_Other,academic_level_Postgraduate,academic_level_Undergraduate,internet_quality_Good,internet_quality_Poor
1501,21,1.69,1.27,2.03,3.01,0.93,7.76,9.30,141,2,...,10,33.02,34.29,49.20,False,False,True,False,True,False
2586,22,5.83,1.85,1.52,3.00,0.88,6.89,13.89,41,37,...,6,30.61,76.88,32.73,False,True,False,False,False,False
2653,23,2.97,0.67,2.80,1.72,0.75,5.00,7.78,10,444,...,7,34.04,60.70,34.98,False,False,False,False,True,False
1055,20,5.06,1.40,2.57,3.23,1.72,7.57,7.29,146,300,...,10,30.69,49.63,61.26,True,False,False,False,True,False
705,19,4.36,2.25,1.19,0.24,1.89,6.49,10.59,100,185,...,6,32.55,40.06,33.99,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4711,23,5.58,2.58,1.56,4.78,3.46,8.01,9.64,84,237,...,7,34.34,63.85,48.35,True,False,False,True,False,True
2313,24,4.51,4.56,4.21,2.44,2.20,7.05,10.97,42,16,...,5,34.82,49.19,38.50,False,True,False,True,True,False
3214,17,5.73,1.03,2.08,2.79,0.86,8.15,10.37,9,159,...,7,42.98,30.16,66.56,False,True,True,False,False,True
2732,21,4.91,1.87,2.53,0.04,2.11,5.49,6.41,1,207,...,9,44.49,52.79,54.11,False,False,False,False,True,False
1926,20,5.54,0.45,3.25,1.19,0.89,7.19,3.08,100,1,...,4,26.94,27.57,44.68,False,False,False,True,False,False

In [ ]:
y_test

1501    1
2586    0
2653    0
1055    1
705     1
       ..
4711    1
2313    1
3214    1
2732    1
1926    1
Name: exam_performance, Length: 1000, dtype: int64

In [ ]:
y_train

4227    1
4676    1
800     1
3671    0
4193    1
       ..
4426    0
466     1
3092    1
3772    0
860     0
Name: exam_performance, Length: 4000, dtype: int64

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(X_train,y_train)
X_test.columns = X_test.columns.str.replace(' ', '')
y_pred=svc.predict(X_test)
print('Model accuracy score with default hyperparamenters:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with default hyperparamenters:{0:0.4f} 0.876

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('confusion_matrix')
cm = confusion_matrix(y_test,y_pred)
print(cm)

confusion_matrix
[[446  63]
 [ 61 430]]

In [ ]:
print('accuracy_score')
print(accuracy_score(y_test,y_pred))

accuracy_score
0.876

In [ ]:
from sklearn.metrics import classification_report
print('classification_report')
print(classification_report(y_test,y_pred))

classification_report
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       509
           1       0.87      0.88      0.87       491

    accuracy                           0.88      1000
   macro avg       0.88      0.88      0.88      1000
weighted avg       0.88      0.88      0.88      1000

In [ ]:
svc=SVC(C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0:{0:0.4f} 0.875

In [ ]:
svc=SVC(C=1200.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=1200.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1200.0:{0:0.4f} 0.87

In [ ]:
linear_kernel=SVC(kernel='linear',C=1.0)
linear_kernel.fit(X_train,y_train)
y_pred_test =linear_kernel.predict(X_test)

In [ ]:
poly_svc=SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train,y_train)
y_pred_test =poly_svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=1.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1.0:{0:0.4f} 0.875

In [ ]:
sigmoid_csv=SVC(kernel='sigmoid',C=100)
sigmoid_csv.fit(X_train,y_train)
y_pred =sigmoid_csv.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0,gamma=1.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0,gamma=1.0:{0:0.4f} 0.538

In [ ]:
sigmoid_csv=SVC(kernel='sigmoid',C=1000)
sigmoid_csv.fit(X_train,y_train)
y_pred =sigmoid_csv.predict(X_test)
print('Model accuracy score with rbf kernel and C=1000.0,gamma=1.0:{0:0.4f}',format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1000.0,gamma=1.0:{0:0.4f} 0.538